title: Haider Bouallegue
logo: https://github.com/YariInCs/Yari.github.io/blob/fe568c44eaebd0c9e46b0c3233d3ecb5c7a24ff5/Images/20240121_042016.jpg
#description: text below image
show_downloads: True
theme: jekyll-theme-minimal
