title: [Haider Bouallegue]
tagline: [this is a website made to show case my work]
#description: [A short description of your site's purpose (e.g. for search engines)]
show_downloads: True
theme: jekyll-theme-midnight
